# Generated by Django 4.2.7 on 2024-01-13 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='birthdate',
            new_name='birth_date',
        ),
    ]
