# Generated by Django 4.2.7 on 2024-01-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_campaign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='booster_required',
        ),
        migrations.AddField(
            model_name='vaccine',
            name='dose_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
