# Generated by Django 4.2.7 on 2024-01-14 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_useraccount_user'),
        ('vaccine_campaign', '0002_remove_vaccine_booster_required_vaccine_dose_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='userAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccine', to='accounts.useraccount'),
        ),
    ]
