# Generated by Django 4.2.7 on 2024-01-14 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_campaign', '0003_vaccine_useraccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccine',
            old_name='userAccount',
            new_name='user_account',
        ),
    ]
