# Generated by Django 4.2.7 on 2024-01-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_campaign', '0004_rename_useraccount_vaccine_user_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='vaccines_offered',
        ),
        migrations.AddField(
            model_name='vaccine',
            name='campaign',
            field=models.ManyToManyField(related_name='campaign', to='vaccine_campaign.campaign'),
        ),
    ]
