# Generated by Django 4.2.7 on 2024-01-15 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vaccine_campaign', '0006_availabletime_dosebooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosebooking',
            name='vaccine',
        ),
        migrations.AlterField(
            model_name='dosebooking',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
